### PR TITLE
Fixed HTTPoxy vulnerability ref #251

### PR DESCRIPTION
**Pull request by kkomelin**
More info https://httpoxy.org

### CODE REVIEW

**Comment by IslandUsurper** [comment]
I think you also need to add that line to `apps/drupal/fastcgi_drupal.conf` and `apps/drupal/fastcgi_no_args_drupal.conf`. I don't see any indication that those two files load the root `fastcgi_params` file.

**Comment by IslandUsurper** [comment]
No, sorry. I am wrong. The file you changed is included in the "http" block, and covers every request. I guess the two files I mentioned are for overrides.

**Comment by perusio** [comment]
@kkomelin Merged with minor style changes. I prefer single quotes and punctuation in comments :)

See https://github.com/perusio/drupal-with-nginx/commit/a7e8dad46419d808021c938d6e2af29f9edda350 and also in master https://github.com/perusio/drupal-with-nginx/commit/ce644102fa29edd1a2c3ef46ae64ff371a992a37

Thanks

**Comment by kkomelin** [comment]
@perusio Thanks for reviewing and merging the PR.
As for the coding standards, it is good to know.

**Pull request closed without merging**
