### PR TITLE
Add handling for modules that like to access index.php directly

### PR DESCRIPTION
**Pull request by ghost**
For example, autocomplete taxonomy wants to access index.php and cannot. This rewrites the URL so it can. Also handles Drupal security issue people experienced earlier in the year.

Relates to issue (https://github.com/perusio/drupal-with-nginx/issues/241)

### CODE REVIEW

**Comment by ghost** [comment]
@perusio not sure if you want it to return 404 if there are no arguments to index.php, or have it try via drupal handler.

**Comment by emjayess** [comment]
Could you please provide a link to the taxonomy autocomplete module project page that you are referencing? And does this patch address Drupal 7 configuration?

**Comment by ghost** [comment]
Hi @emjayess this is from Drupal 7 core code: https://www.drupal.org/node/854216
This addresses Drupal 7 configuration. I'm not sure about Drupal 6. Have nothing to test that code on.

**Comment by ghost** [comment]
OK maybe the title is was wrong. The drupal core code has autocomplete that accesses index.php directly. Also the patch for https://www.drupal.org/SA-CORE-2015-003 affected things too.
I'm not a drupal developer, just a sysadmin.

**Comment by iryston** [comment]
@tdm4 this commit doesn't works at my server.
I still receive an error.

An AJAX HTTP error occurred.
HTTP Result Code: 404
Debugging information follows.
Path: http://www.example.com/index.php?q=taxonomy/autocomplete/field_subjects
StatusText: Not Found
ResponseText: 
404 Not Found
404 Not Found
nginx

**Comment by iryston** [comment]
To prevent allowing direct access to index.php is written a little module [Autocomplete Unblock](https://www.drupal.org/sandbox/irystonnet/2821464)
The sandbox project is located at https://www.drupal.org/sandbox/irystonnet/2821464

Opened issue on Drupal.org Project applications https://www.drupal.org/node/2821473

To use it just clone to modules directory and enable.

```
git clone --branch 7.x-1.x https://git.drupal.org/sandbox/iryston.net/2821464.git autocomplete_unblock
```

**Comment by acrolink** [comment]
Would you please confirm that this issue cannot be fixed by some modification to the Nginx configuration files provided by `drupal-with-nginx` repo, without the need to install the above mentioned sandbox Drupal module? Thank you.

**Comment by iryston** [comment]
@acrolink  this issue can be fixed as described in  [this comment](https://www.drupal.org/node/2599326#comment-10828976)
But, I don't think that allowing direct access to index.php is the preferred choice.

**Comment by ghost** [comment]
Closing this as an agreement cannot be reached.

**Pull request closed without merging**
