### PR TITLE
Fixed HTTPoxy vulnerability ref #251

### PR DESCRIPTION
**Pull request by kkomelin**
More info https://httpoxy.org

### CODE REVIEW

**Comment by kkomelin** [comment]
Accidentally included redundant commit, closing this PR in order to create a correct one.

**Comment by rfay** [comment]
Just FYI in the future you can force-push into your PR to update it before it's pulled.

**Comment by kkomelin** [comment]
Thanks @rfay. This is the first time I deal with such collision. Could you please refer to documentation?

**Comment by kkomelin** [comment]
Here is the correct PR https://github.com/perusio/drupal-with-nginx/pull/253

**Comment by rfay** [comment]
git commit --amend (or rebase, or whatever)
git push --force (into your own fork, which is where the PR lives)

**Pull request closed without merging**
