### PR TITLE
Add woff2 extention to directly served static files

### PR DESCRIPTION
**Pull request by iryston**
This commit fixes fonts loading problems in certain configurations.

### CODE REVIEW

**Comment by kkomelin** [comment]
I met this issue with Glyphicon icon font, which is included in some versions of Bootstrap framework by default.

**Comment by iryston** [comment]
@kkomelin I had issues with Font Awesome and Google icons too.

**Comment by kkomelin** [comment]
So I vote for this PR

**Comment by iryston** [comment]
Thanks!

**Comment by kkomelin** [comment]
@perusio Could you please take a look at this PR when you have time. Thanks.

**Comment by pprishchepa** [comment]
@iryston What about woff2 in mime.types? It's only woff there.

**Comment by kkomelin** [comment]
Good point @PavelPrischepa

**Comment by iryston** [comment]
@PavelPrischepa thank you for PR! I want to pay attention that according to w3c [recommendation](https://dev.w3.org/webfonts/WOFF2/spec/#IMT) WOFF 2.0 is an improvement on WOFF 1.0. The two formats have different Internet Media Types and may be used in parallel.
So, WOFF2 mime type should be

```
application/font-woff2                 woff2;
```

**Comment by perusio** [comment]
@iryston I committed support for woff2 using `woff2?`  instead of another option in the group.
Thanks for your PR. 
https://github.com/perusio/drupal-with-nginx/commit/747fc306b86ff772829265ab475de7b9825aff7e

**Comment by iryston** [comment]
@perusio thanks for your commit.

**Pull request closed without merging**
