### PR TITLE
Added an appropriate mime type for .woff2

### PR DESCRIPTION
**Pull request by pprishchepa**
Related PR #255.

### CODE REVIEW

**Comment by iryston** [comment]
@PavelPrischepa thank you for PR! I want to pay attention that according to w3c [recommendation](https://dev.w3.org/webfonts/WOFF2/spec/#IMT) WOFF 2.0 is an improvement on WOFF 1.0. The two formats have different Internet Media Types and may be used in parallel.
So, WOFF2 mime type should be

```
application/font-woff2                 woff2;
```

**Comment by pprishchepa** [comment]
@iryston Thank you for the remark. But I'm not sure, Is there any way to change the PR, or do I need to create a new one?

**Comment by iryston** [comment]
To update a PR, even if you have removed the original remote branch out of which the PR was created, you just need to:
- Fetch the PR (`git fetch pull/<id>/head:branchname` and `git checkout branchname`).
- Add new commits, amend, rebase, do whatever you like.
- Push or push force (`git push remote +branch`).

And after that the PR will be automagically updated

**Comment by perusio** [comment]
- Thanks.

**Comment by iryston** [comment]
@perusio can you change
`application/font-woff                 woff2;`
to
`application/font-woff2                 woff2;`
or it will be better to make a new PR?

**Pull request merged**
